 INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Action and Adventure');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Classics');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Comic Book or Graphic Novel');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Detective and Mystery');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Fantasy');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Historical Fiction');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Horror');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Literary Fiction');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Romance');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Science Fiction (Sci-Fi)');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Short Stories');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Suspense and Thrillers');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ("Women's Fiction");
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Biographies and Autobiographies');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Cookbooks');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Essays');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('History');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Memoir');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Poetry');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('Self-Help');
INSERT INTO app_generic_views_bookcategory (category_name) VALUES ('True Crime');